version: '3.8'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - static:/backend_static
    depends_on:
      - db
    restart: always
    env_file: .env


